export interface Category {
  key: string;
  label: string;
  p8Label: string;
  description: string;
  examples: string[];
  color: string;
  deductible: 'yes' | 'no' | 'review';
}

export const CATEGORIES: Category[] = [
  {
    key: 'cost_of_sales',
    label: 'Cost of Sales',
    p8Label: 'P8 – Cost of Sales',
    description: 'Purchases of stock, raw materials, or goods acquired for resale or use in producing income.',
    examples: ['wholesale purchases', 'raw materials', 'inventory', 'goods for resale', 'freight inwards'],
    color: '#3B82F6',
    deductible: 'yes',
  },
  {
    key: 'contractor_expenses',
    label: 'Contractor & Commission Expenses',
    p8Label: 'P8 – Contractor, sub-contractor and commission expenses',
    description: 'Payments to subcontractors, freelancers, labour-hire, or sales commissions paid out.',
    examples: ['subcontractor invoice', 'freelancer payment', 'labour hire', 'sales commission', 'contract worker'],
    color: '#8B5CF6',
    deductible: 'yes',
  },
  {
    key: 'superannuation',
    label: 'Superannuation Expenses',
    p8Label: 'P8 – Superannuation expenses',
    description: 'Super contributions made for employees or yourself.',
    examples: ['AustralianSuper', 'REST Super', 'HESTA', 'super contribution', 'SMSF', 'superannuation fund'],
    color: '#6366F1',
    deductible: 'yes',
  },
  {
    key: 'lease_expenses',
    label: 'Lease Expenses',
    p8Label: 'P8 – Lease expenses',
    description: 'Leasing costs for equipment, machinery, or vehicles (not real estate).',
    examples: ['equipment lease', 'vehicle lease', 'photocopier lease', 'plant hire', 'machinery hire'],
    color: '#06B6D4',
    deductible: 'yes',
  },
  {
    key: 'rent_expenses',
    label: 'Rent Expenses',
    p8Label: 'P8 – Rent expenses',
    description: 'Rent paid for business premises, office space, or commercial property.',
    examples: ['office rent', 'workshop rent', 'commercial lease', 'premises rent', 'storage unit rent'],
    color: '#14B8A6',
    deductible: 'yes',
  },
  {
    key: 'interest_expenses',
    label: 'Interest Expenses',
    p8Label: 'P8 – Interest expenses',
    description: 'Interest on business loans, credit facilities, or equipment finance.',
    examples: ['business loan interest', 'line of credit interest', 'equipment finance interest', 'overdraft interest'],
    color: '#F97316',
    deductible: 'yes',
  },
  {
    key: 'depreciation',
    label: 'Depreciation Expenses',
    p8Label: 'P8 – Depreciation expenses',
    description: 'Depreciation or instant asset write-off for business assets and equipment.',
    examples: ['laptop purchase', 'machinery', 'vehicle depreciation', 'capital equipment', 'business asset'],
    color: '#64748B',
    deductible: 'yes',
  },
  {
    key: 'motor_vehicle',
    label: 'Motor Vehicle Expenses',
    p8Label: 'P8 – Motor vehicle expenses',
    description: 'Fuel, registration, servicing, insurance, and other costs for business vehicles.',
    examples: ['Caltex', 'BP', 'Shell', 'Ampol', '7-Eleven fuel', 'car registration', 'NRMA', 'vehicle service', 'Bridgestone', 'tyres'],
    color: '#10B981',
    deductible: 'yes',
  },
  {
    key: 'repairs_maintenance',
    label: 'Repairs & Maintenance',
    p8Label: 'P8 – Repairs and maintenance',
    description: 'Repairs and maintenance to business equipment, tools, or premises.',
    examples: ['equipment repair', 'plumber for office', 'maintenance service', 'tool repair', 'premises maintenance'],
    color: '#84CC16',
    deductible: 'yes',
  },
  {
    key: 'bad_debts',
    label: 'Bad Debts',
    p8Label: 'P8 – Bad debts',
    description: 'Amounts written off as irrecoverable bad debts from business debtors.',
    examples: ['bad debt write-off', 'irrecoverable debt'],
    color: '#F43F5E',
    deductible: 'yes',
  },
  {
    key: 'advertising_marketing',
    label: 'Advertising & Marketing',
    p8Label: 'P8 – All other expenses (Advertising & Marketing)',
    description: 'Advertising spend, marketing services, and promotional materials.',
    examples: ['Google Ads', 'Facebook Ads', 'Meta Ads', 'Instagram Ads', 'LinkedIn Ads', 'printing', 'signage', 'promotional materials', 'marketing agency'],
    color: '#EC4899',
    deductible: 'yes',
  },
  {
    key: 'bank_charges',
    label: 'Bank Charges & Fees',
    p8Label: 'P8 – All other expenses (Bank Charges & Fees)',
    description: 'Bank account fees, merchant fees, and payment processing fees.',
    examples: ['account keeping fee', 'monthly fee', 'EFTPOS fee', 'Stripe', 'Square', 'PayPal fee', 'merchant fee', 'transaction fee', 'bank charge'],
    color: '#9CA3AF',
    deductible: 'yes',
  },
  {
    key: 'home_office',
    label: 'Home Office Expenses',
    p8Label: 'P8 – All other expenses (Home Office)',
    description: 'Business portion of home costs when operating from home: utilities, internet.',
    examples: ['home internet business portion', 'electricity home office', 'home phone business use'],
    color: '#22C55E',
    deductible: 'yes',
  },
  {
    key: 'insurance',
    label: 'Insurance',
    p8Label: 'P8 – All other expenses (Insurance)',
    description: 'Business insurance premiums including professional indemnity, public liability, and trade insurance.',
    examples: ['professional indemnity', 'public liability', 'business insurance', 'trade insurance', 'income protection', 'CGU', 'Allianz business', 'QBE', 'Suncorp business'],
    color: '#0EA5E9',
    deductible: 'yes',
  },
  {
    key: 'phone_internet',
    label: 'Phone & Internet',
    p8Label: 'P8 – All other expenses (Phone & Internet)',
    description: 'Business phone and internet service bills.',
    examples: ['Telstra', 'Optus', 'Vodafone', 'TPG', 'iiNet', 'Aussie Broadband', 'phone bill', 'internet bill', 'mobile plan business'],
    color: '#38BDF8',
    deductible: 'yes',
  },
  {
    key: 'professional_fees',
    label: 'Professional Fees',
    p8Label: 'P8 – All other expenses (Professional Fees)',
    description: 'Accounting, bookkeeping, legal, and other professional advisory services.',
    examples: ['accountant', 'bookkeeper', 'solicitor', 'lawyer', 'BAS agent', 'tax agent', 'consulting fee', 'advisory fee'],
    color: '#A78BFA',
    deductible: 'yes',
  },
  {
    key: 'stationery_supplies',
    label: 'Stationery & Office Supplies',
    p8Label: 'P8 – All other expenses (Stationery & Supplies)',
    description: 'Office consumables, stationery, postage, and printing supplies.',
    examples: ['Officeworks', 'paper', 'printer ink', 'postage', 'Australia Post', 'stationery', 'envelopes', 'stamps'],
    color: '#FCD34D',
    deductible: 'yes',
  },
  {
    key: 'software_subscriptions',
    label: 'Software & Subscriptions',
    p8Label: 'P8 – All other expenses (Software & Subscriptions)',
    description: 'Software licences, SaaS tools, and digital business subscriptions.',
    examples: ['Xero', 'MYOB', 'Adobe', 'Microsoft 365', 'Canva', 'Dropbox', 'Atlassian', 'AWS', 'Google Workspace', 'Slack', 'Zoom', 'GitHub', 'Shopify', 'Squarespace'],
    color: '#818CF8',
    deductible: 'yes',
  },
  {
    key: 'travel_accommodation',
    label: 'Travel & Accommodation',
    p8Label: 'P8 – All other expenses (Travel & Accommodation)',
    description: 'Business travel including flights, hotels, and ground transport on business trips.',
    examples: ['Qantas', 'Virgin Australia', 'Jetstar', 'Rex Airlines', 'hotel', 'Airbnb business', 'taxi business', 'parking business'],
    color: '#FB923C',
    deductible: 'yes',
  },
  {
    key: 'training_education',
    label: 'Training & Self-Education',
    p8Label: 'P8 – All other expenses (Training & Education)',
    description: 'Courses, workshops, and professional development directly related to your business.',
    examples: ['Udemy', 'LinkedIn Learning', 'conference registration', 'industry workshop', 'professional development', 'training course', 'seminar'],
    color: '#C084FC',
    deductible: 'yes',
  },
  {
    key: 'uniforms_clothing',
    label: 'Uniforms & Protective Clothing',
    p8Label: 'P8 – All other expenses (Uniforms & Clothing)',
    description: 'Work-specific uniforms, PPE, and safety clothing required for your trade.',
    examples: ['safety boots', 'hi-vis vest', 'work uniform', 'branded work shirts', 'protective equipment', 'PPE', 'safety gear', 'Workwear'],
    color: '#34D399',
    deductible: 'yes',
  },
  {
    key: 'tools_equipment',
    label: 'Tools & Equipment',
    p8Label: 'P8 – All other expenses (Tools & Equipment)',
    description: 'Small tools and equipment for business use, typically under the instant asset write-off threshold.',
    examples: ['power tools', 'hand tools', 'computer peripherals', 'trade tools', 'Bunnings tools', 'Mitre 10', 'Total Tools'],
    color: '#A3E635',
    deductible: 'yes',
  },
  {
    key: 'not_deductible',
    label: 'Not Deductible',
    p8Label: 'Not a tax deduction',
    description: 'Personal expenses with no business connection, tax payments, or entertainment.',
    examples: ['groceries', 'Coles', 'Woolworths personal', 'ALDI', 'Netflix', 'Spotify', 'entertainment', 'restaurant personal', 'ATO payment', 'gym', 'clothing personal', 'holiday personal'],
    color: '#EF4444',
    deductible: 'no',
  },
  {
    key: 'needs_review',
    label: 'Needs Review',
    p8Label: 'Ambiguous – manual review required',
    description: 'Transactions that could be business or personal depending on context. Requires manual review.',
    examples: ['Woolworths', 'Coles', 'Uber', 'Lyft', 'cash withdrawal', 'ATM', 'Amazon', 'eBay', 'JB Hi-Fi', 'Harvey Norman'],
    color: '#F59E0B',
    deductible: 'review',
  },
];

export const CATEGORY_MAP = Object.fromEntries(CATEGORIES.map((c) => [c.key, c]));

export const CATEGORY_KEYS = CATEGORIES.map((c) => c.key);

export function getCategoryByKey(key: string): Category {
  return CATEGORY_MAP[key] ?? CATEGORIES.find((c) => c.key === 'needs_review')!;
}
